name: Generate Skills Map

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_skills_map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install graphviz

      - name: Generate Skills Map
        run: |
          python .github/workflows/generate_skills_map.py

      - name: Upload Skills Map
        uses: actions/upload-artifact@v3
        with:
          name: skills_map
          path: skills_map.png
          
      - name: Commit and push Skills Map
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add skills_map.png
          git commit -m "Add generated skills map" || echo "No changes to commit"
          git push origin main
